version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ui/MoodTracker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/service/MoodTracker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directories:
      - "/service"
      - "/ui"
      - "/db"
    schedule:
      interval: "weekly"
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
